### ISSUE TITLE
fio-plot 1.1.0 cannot handle numJobs > 1 on data produced by bench-fio. fio-plot 1.0.22 worked fine.

### ISSUE THREAD

**Issue by adashofme** [louwrentius/fio-plot#104]
This is what my bash script looks like:

```
mode="randread randwrite"
blockSizes="4k 64k"
queueDepths="2 16 64"
numJobs="4"
testTime="60"
cpumask="225"

sudo bench-fio -d /dev/nvme0n1 -o $filename -t device --mode $mode --size 1G -b $blockSizes --iodepth $queueDepths --numjobs $numJobs --direct 1 --engine libaio --runtime $testTime --destructive --time-based -p --loops 0 --extra-opts cpumask=$cpumask

    sudo fio-plot -i ./$filename/nvme0n1/4k -T "$title" -l -r randread -d $queueDepths -n $numJobs --show-cpu -o "$filename/4k-randread.png"
    sudo fio-plot -i ./$filename/nvme0n1/64k -T "$title" -l -r randread -d $queueDepths -n $numJobs --show-cpu -o "$filename/64k-randread.png"
    sudo fio-plot -i ./$filename/nvme0n1/4k -T "$title" -l -r randwrite -d $queueDepths -n $numJobs --show-cpu -o "$filename/4k-randwrite.png"
    sudo fio-plot -i ./$filename/nvme0n1/64k -T "$title" -l -r randwrite -d $queueDepths -n $numJobs --show-cpu -o "$filename/64k-randwrite.png"

    sudo fio-plot -i ./$filename/nvme0n1/4k -T "$title" -g -t iops lat -r randread -d $queueDepths -n $numJobs --xlabel-parent 0 -o "$filename/4krandread-timeplot.png"
    sudo fio-plot -i ./$filename/nvme0n1/64k -T "$title" -g -t iops lat -r randread -d $queueDepths -n $numJobs --xlabel-parent 0 -o "$filename/64krandread-timeplot.png"
    sudo fio-plot -i ./$filename/nvme0n1/4k -T "$title" -g -t iops lat -r randwrite -d $queueDepths -n $numJobs --xlabel-parent 0 -o "$filename/4krandwrite-timeplot.png"
    sudo fio-plot -i ./$filename/nvme0n1/64k -T "$title" -g -t iops lat -r randwrite -d $queueDepths -n $numJobs --xlabel-parent 0 -o "$filename/64krandwrite-timeplot.png"
```

I only have issues with the iops vs latency graphs. The timeplots are produced just fine. When trying to produce the iops vs latency 2d bar charts, this is the error I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/fio-plot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/__init__.py", line 41, in main
    routing_dict[graphtype]["function"](settings, data)
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/fiolib/bar2d.py", line 116, in chart_2dbarchart_jsonlogdata
    return_data = create_bars_and_xlabels(settings, data, ax1, ax3)
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/fiolib/bar2d.py", line 88, in create_bars_and_xlabels
    ax1.set_xticklabels(labels=x_axis, fontsize=fontsize,)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py", line 74, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/_api/deprecation.py", line 297, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py", line 1969, in set_ticklabels
    raise ValueError(
ValueError: The number of FixedLocator locations (12), usually from a call to set_ticks, does not match the number of labels (3).
```

I've worked around this by reverting to fio-plot version 1.0.22 for now.
Edit: the script works fine when numJobs=1 on the new version too

**Comment by louwrentius** [comment]
Thanks for the feedback, I will take a look.

**Comment by louwrentius** [comment]
I've generated some test data based on your examples. I'm now able to generate this output. 
![test](https://user-images.githubusercontent.com/1312044/228697407-f69e2f72-df50-455d-88c3-6bff08438a3f.png)

**Comment by louwrentius** [comment]
We're now at 1.1.3 after some fixes. I'm closing this one out, if you still have the same issues let me know.
