### ISSUE TITLE
rich.errors.LiveError: Only one live display may be active at once when running with fio-plot v1.1.11

### ISSUE THREAD

**Issue by enkka** [louwrentius/fio-plot#129]
```
                          Bench-fio                           
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Setting                        ┃ value                     ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ Estimated Duration             │ 0:10:00                   │
│ Number of benchmarks           │ 2                         │
│ Test target(s)                 │ /dev/nvme0n1 /dev/nvme1n1 │
│ Target type                    │ device                    │
│ I/O Engine                     │ libaio                    │
│ Test mode (read/write)         │ write                     │
│ Block size                     │ 1m                        │
│ IOdepth to be tested           │ 32                        │
│ NumJobs to be tested           │ 1                         │
│ Time duration per test (s)     │ 600                       │
│ Benchmark loops                │ 1                         │
│ Time based                     │ True                      │
│ Direct I/O                     │ 1                         │
│ Output folder                  │ ./20231203-222609         │
│ Log interval of perf data (ms) │ 1000                      │
│ Invalidate buffer cache        │ 1                         │
│ Allow destructive writes       │ True                      │
│ Check remote timeout (s)       │ 2                         │
│ Testing devices in parallel    │ True                      │
└────────────────────────────────┴───────────────────────────┘
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/bench_fio/benchlib/runfio.py", line 125, in worker
    for benchmark in progress_benchmarks:
  File "/usr/local/lib/python3.9/site-packages/bench_fio/benchlib/runfio.py", line 156, in ProgressBar
    for step in track(iterable, description="", refresh_per_second=0.5):
  File "/usr/local/lib/python3.9/site-packages/rich/progress.py", line 167, in track
    with progress:
  File "/usr/local/lib/python3.9/site-packages/rich/progress.py", line 1168, in __enter__
    self.start()
  File "/usr/local/lib/python3.9/site-packages/rich/progress.py", line 1159, in start
    self.live.start(refresh=True)
  File "/usr/local/lib/python3.9/site-packages/rich/live.py", line 113, in start
    self.console.set_live(self)
  File "/usr/local/lib/python3.9/site-packages/rich/console.py", line 836, in set_live
    raise errors.LiveError("Only one live display may be active at once")
rich.errors.LiveError: Only one live display may be active at once
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:10:00

```

my os info

```
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

```
```
[root@localhost ~]# pip3 list | grep rich
rich                13.7.0
```

**Comment by louwrentius** [comment]
Thanks Enka, I think I released something broken 😳

**Comment by enkka** [comment]
> Thanks Enka, I think I released something broken 😳

U r welcome, thanks for this tool, it really helps me on testing.

**Comment by louwrentius** [comment]
I've found time to fix the issue. Let me know if the latest version works for you (1.1.12).

<img width="567" alt="Screenshot 2023-12-10 at 01 37 30" src="https://github.com/louwrentius/fio-plot/assets/1312044/4cb7d0f0-e1c4-44ae-a7c2-0d999b0bedd5">

**Comment by louwrentius** [comment]
I'm closing this issue, feel free to reopen if the issue persists.
