### ISSUE TITLE
-t bw option produces an error on fio_plot

### ISSUE THREAD

**Issue by nwilson666** [louwrentius/fio-plot#14]
when I use the -t bw to get bandwidth, it give me an error - lat and iops work options work fine.

Traceback (most recent call last):
  File "./fio_plot", line 135, in <module>
    main()
  File "./fio_plot", line 123, in main
    uses_json_files[item](settings, parsed_data)
  File "/spice/data/users/itnw/fio-plot-master/fio_plot/fiolib/bar3d.py", line 28, in plot_3d
    rw, metric)
  File "/spice/data/users/itnw/fio-plot-master/fio_plot/fiolib/shared_chart.py", line 45, in get_record_set_3d
    row.append(record[metric])
KeyError: 'bw'

**Comment by louwrentius** [comment]
Thanks, the -t option for 3dGraphs only supports iops and lat no bw. For now, you could just use IOPS as IOPS x block size = bandwidth. 

I should either implement it and in the mean time maybe gracefully handle this error.
