### ISSUE TITLE
KeyError: 'job options'

### ISSUE THREAD

**Issue by GT-Anakin** [louwrentius/fio-plot#2]
Hi,

i just wanted to run that plotting script, but it seams not to work. Any ideas about what i did wrong??

```
D:\FIO\fio-plot-master>fio-plot.py -i ../Plots -s performance_hw0.json -H
Traceback (most recent call last):
  File "D:\FIO\fio-plot-master\fio-plot.py", line 320, in <module>
    main()
  File "D:\FIO\fio-plot-master\fio-plot.py", line 310, in main
    b.chart_latency_histogram('read')
  File "D:\FIO\fio-plot-master\fio-plot.py", line 262, in chart_latency_histogram
    stats = self.getStats(mode)
  File "D:\FIO\fio-plot-master\fio-plot.py", line 244, in getStats
    depth = record['jobs'][0]['job options']['iodepth'].lstrip("0")
KeyError: 'job options'

```

**Comment by louwrentius** [comment]
months late reply: I'm working on a new version, I'm not sure what is going on here.

**Comment by afreiberger** [comment]
This issue is related to using global options rather than having per-job iodepth or rw modes set.  I've provided #3 to resolve.

**Comment by louwrentius** [comment]
I have released a newer version.
