### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rubin55** [louwrentius/fio-plot#32]
After running the following `bench_fio` invocation:

```
./bench_fio --target /root/test --type directory --size 500MiB --output /root/out --iodepth 1 2 4 8 16 32 --numjobs 1 2 4 8 16 32 --rwmixread 50 --direct 1 --invalidate 1 --engine posixaio
```
Followed by this `fio_plot` command (using `-L` to request the 3D graph):

```
./fio_plot  -i ../../edge/  -L -r randread -T Test
```

I'm getting the following error from `fio_plot`:

```
Traceback (most recent call last):
  File "./fio_plot", line 180, in <module>
    main()
  File "./fio_plot", line 147, in main
    run_preflight_checks(settings)
  File "./fio_plot", line 123, in run_preflight_checks
    if settings['type'][0] not in ['iops', 'lat']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by rubin55** [comment]
I just discovered you can/have-to also specify either `iops` or `lat` with the `-t` option.

**Comment by louwrentius** [comment]
I've improved the error handling and it now explains to you what must be done if you specify -L without -t. Thanks for your report.
