### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by rubin55** [louwrentius/fio-plot#39]
When creating a histogram exactly according to the example command line in README.md (i.e, `fio_plot -i something/4k/ -T "Title" -H -r randread -d 1 -n 1 `), I get the following error:

```
Traceback (most recent call last):
  File "//home/rubin/Syncthing/Source/Other/fio-plot/fio_plot/fio_plot", line 262, in <module>
    main()
  File "//home/rubin/Syncthing/Source/Other/fio-plot/fio_plot/fio_plot", line 250, in main
    uses_json_files[item]['function'](settings, parsed_data)
  File "/mnt/s/Source/Other/fio-plot/fio_plot/fiolib/barhistogram.py", line 120, in chart_latency_histogram
    sourcelength = len(settings['source'])
TypeError: object of type 'NoneType' has no len()
```

**Comment by rubin55** [comment]
probably a missing `    if settings['source']:
`

**Comment by louwrentius** [comment]
Whoops, I already see the bug. If you add -s with some text as argument it will work, I think.

**Comment by louwrentius** [comment]
It was exactly as you predicted.

I've just pushed some fixes to master. I'm closing this issue but if you believe something is still wrong, feel free to reopen it.
