### ISSUE TITLE
plot error when saving png file

### ISSUE THREAD

**Issue by leonanu** [louwrentius/fio-plot#78]
`# fio-plot -i EXASCEND-480G-SATA/sdb/4k --source "LCWT TechLab" -T "EXASCEND 480G SATA - IOPS Random Read" -L -t iops -r randread`

```
/usr/local/lib/python3.10/dist-packages/fio_plot/fiolib/supporting.py:406: UserWarning: Tight layout not applied. The left and right margins cannot be made large enough to accommodate all axes decorations.
  plt.tight_layout(rect=[0, 0, 1, 1])
Traceback (most recent call last):
  File "/usr/local/bin/fio-plot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/__init__.py", line 45, in main
    routing_dict[graphtype]["function"](settings, data)
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/fiolib/bar3d.py", line 197, in plot_3d
    supporting.save_png(settings, plt, fig)
  File "/usr/local/lib/python3.10/dist-packages/fio_plot/fiolib/supporting.py", line 408, in save_png
    savename = f"{title}_{now}_{random}.png" if len(settings["output_filename"]) == 0 else settings["output_filename"]
TypeError: object of type 'NoneType' has no len()
```

**Comment by leonanu** [comment]
Solved by add option -o xxx.png

**Comment by louwrentius** [comment]
Thanks but it is still a bug 🐜
