### ISSUE TITLE
Using multiple blocksize in .ini-file for bench-fio fails

### ISSUE THREAD

**Issue by cmonty14** [louwrentius/fio-plot#90]
Hi,
I have created this .ini-file for bench-fio:
```
[benchfio]
target = /mnt/ssd/fiotest
output = CCLOUD_SSD
type = file
mode = randread,randwrite,randrw
rwmixread = 75
size = 10G
blocksize = 4k,64M
iodepth = 1
numjobs = 1
direct = 1
engine = libaio
precondition = True
precondition_repeat = False
runtime = 60
destructive = True
extra-opts = norandommap=1,refill_buffers=1
```

Running bench-fio fails with this error:
```
                                                   +++ Fio Benchmark Script +++

Estimated duration            : 0:06:00
Test target                   : /mnt/ssd/fiotest
Job template                  : /home/ccloud/.local/lib/python3.10/site-packages/bench_fio/benchlib/../templates/fio-job-template.fio
I/O Engine                    : libaio
Test mode (read/write)        : randread randwrite randrw
IOdepth to be tested          : 1
NumJobs to be tested          : 1
Block size                    : 4k
Direct I/O                    : 1
Specified test data size      : 10G
Run precondition workload     : True
Output folder                 : CCLOUD_SSD
Precondition template         : /home/ccloud/.local/lib/python3.10/site-packages/bench_fio/benchlib/../templates/precondition.fio
Time duration per test (s)    : 60
Benchmark loops               : 1
Log interval of perf data (ms): 1000
Invalidate buffer cache       : 1
Allow destructive writes      : True
Target type                   : file
Traceback (most recent call last):
  File "/home/ccloud/.local/bin/bench-fio", line 8, in <module>
    sys.exit(main())
  File "/home/ccloud/.local/lib/python3.10/site-packages/bench_fio/__init__.py", line 39, in main
    display.display_header(settings, tests)
  File "/home/ccloud/.local/lib/python3.10/site-packages/bench_fio/benchlib/display.py", line 51, in display_header
    description = descriptions[item]
KeyError: 'blocksize'
```

Can you please advise how to fix it?

THX

**Comment by cmonty14** [comment]
Wrong coding in .ini-file
